spring:
  application:
    name: online_shopping
  data:
    mongodb:
      host: mongodb             # Adresse de l'hôte MongoDB
      port: 27017                 # Port par défaut de MongoDB
      database: shopping       # Nom de la base de données MongoDB
      username: root   # Optionnel si l'authentification est nécessaire
      password: donald

  datasource:
    #productcatalog:
    url: jdbc:postgresql://postgres1:5433/shopping
    username: postgres
    password: donald
    hikari:
      maximum-pool-size: 10

    #ordermanagement:
    #  url: jdbc:postgresql://localhost:5432/order_management_db
    #  username: postgres
    #  password: password
    #  driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          highlight_sql: true
          generate_statistics: true

      show-sql: true
server:
  port: 8400
management:
  endpoints:
    web:
      exposure:
        include: "*"
